-- Script de Exclusao das tabelas (Inicio) --

DROP TABLE EQUIPAMENTO CASCADE CONSTRAINT;
DROP TABLE AVALIACAO CASCADE CONSTRAINT;
DROP TABLE TELEFONE CASCADE CONSTRAINT;
DROP TABLE DEPENDENTE CASCADE CONSTRAINT;
DROP TABLE MANUTENCAO CASCADE CONSTRAINT;
DROP TABLE FUNCIONARIO
DROP TABLE VENDA CASCADE CONSTRAINT;
DROP TABLE PRODUTO
DROP TABLE HOSPEDA CASCADE CONSTRAINT;
DROP TABLE RESERVA CASCADE CONSTRAINT;
DROP TABLE QUARTO
DROP TABLE CLIENTE
-- Script de Exclusao das tabelas (Fim) --